export const countryDataCodes = [
  {
    name: "Afghanistan (‫افغانستان‬‎)",
    iso2: "af",
    dialCode: "93",
    priority: 0,
    areaCodes: null,
    countryId: 4,
    nationality: "Afghan",
    continent: "Asia",
  },
  {
    name: "Albania (Shqipëri)",
    iso2: "al",
    dialCode: "355",
    priority: 0,
    areaCodes: null,
    countryId: 8,
    nationality: "Albanian",
    continent: "Europe",
  },
  {
    name: "Algeria (‫الجزائر‬‎)",
    iso2: "dz",
    dialCode: "213",
    priority: 0,
    areaCodes: null,
    countryId: 12,
    nationality: "Algerian",
    continent: "Africa",
  },
  {
    name: "American Samoa",
    iso2: "as",
    dialCode: "1684",
    priority: 0,
    areaCodes: null,
    countryId: 16,
    nationality: "American Samoan",
    continent: "Oceania",
  },
  {
    name: "Andorra",
    iso2: "ad",
    dialCode: "376",
    priority: 0,
    areaCodes: null,
    countryId: 20,
    nationality: "Andorran",
    continent: "Europe",
  },
  {
    name: "Angola",
    iso2: "ao",
    dialCode: "244",
    priority: 0,
    areaCodes: null,
    countryId: 24,
    nationality: "Angolan",
    continent: "Africa",
  },
  {
    name: "Anguilla",
    iso2: "ai",
    dialCode: "1264",
    priority: 0,
    areaCodes: null,
    countryId: 660,
    nationality: "Anguillan",
    continent: "North America",
  },
  {
    name: "Antigua and Barbuda",
    iso2: "ag",
    dialCode: "1268",
    priority: 0,
    areaCodes: null,
    countryId: 28,
    nationality: "of Antigua and Barbuda",
    continent: "North America",
  },
  {
    name: "Argentina",
    iso2: "ar",
    dialCode: "54",
    priority: 0,
    areaCodes: null,
    countryId: 32,
    nationality: "Argentine",
    continent: "South America",
  },
  {
    name: "Armenia (Հայաստան)",
    iso2: "am",
    dialCode: "374",
    priority: 0,
    areaCodes: null,
    countryId: 51,
    nationality: "Armenian",
    continent: "Asia",
  },
  {
    name: "Aruba",
    iso2: "aw",
    dialCode: "297",
    priority: 0,
    areaCodes: null,
    countryId: 533,
    nationality: "Aruban",
    continent: "North America",
  },
  {
    name: "Australia",
    iso2: "au",
    dialCode: "61",
    priority: 0,
    areaCodes: null,
    countryId: 36,
    nationality: "Australian",
    continent: "Oceania",
  },
  {
    name: "Austria (Österreich)",
    iso2: "at",
    dialCode: "43",
    priority: 0,
    areaCodes: null,
    countryId: 40,
    nationality: "Austrian",
    continent: "Europe",
  },
  {
    name: "Azerbaijan (Azərbaycan)",
    iso2: "az",
    dialCode: "994",
    priority: 0,
    areaCodes: null,
    countryId: 31,
    nationality: "Azerbaijani",
    continent: "Asia",
  },
  {
    name: "Bahamas",
    iso2: "bs",
    dialCode: "1242",
    priority: 0,
    areaCodes: null,
    countryId: 44,
    nationality: "Bahamian",
    continent: "North America",
  },
  {
    name: "Bahrain (‫البحرين‬‎)",
    iso2: "bh",
    dialCode: "973",
    priority: 0,
    areaCodes: null,
    countryId: 48,
    nationality: "Bahraini",
    continent: "Asia",
  },
  {
    name: "Bangladesh (বাংলাদেশ)",
    iso2: "bd",
    dialCode: "880",
    priority: 0,
    areaCodes: null,
    countryId: 50,
    nationality: "Bangladeshi",
    continent: "Asia",
  },
  {
    name: "Barbados",
    iso2: "bb",
    dialCode: "1246",
    priority: 0,
    areaCodes: null,
    countryId: 52,
    nationality: "Barbadian",
    continent: "North America",
  },
  {
    name: "Belarus (Беларусь)",
    iso2: "by",
    dialCode: "375",
    priority: 0,
    areaCodes: null,
    countryId: 112,
    nationality: "Belarusian",
    continent: "Europe",
  },
  {
    name: "Belgium (België)",
    iso2: "be",
    dialCode: "32",
    priority: 0,
    areaCodes: null,
    countryId: 56,
    nationality: "Belgian",
    continent: "Europe",
  },
  {
    name: "Belize",
    iso2: "bz",
    dialCode: "501",
    priority: 0,
    areaCodes: null,
    countryId: 84,
    nationality: "Belizean",
    continent: "North America",
  },
  {
    name: "Benin (Bénin)",
    iso2: "bj",
    dialCode: "229",
    priority: 0,
    areaCodes: null,
    countryId: 204,
    nationality: "Beninese",
    continent: "Africa",
  },
  {
    name: "Bermuda",
    iso2: "bm",
    dialCode: "1441",
    priority: 0,
    areaCodes: null,
    countryId: 60,
    nationality: "Bermudian",
    continent: "North America",
  },
  {
    name: "Bhutan (འབྲུག)",
    iso2: "bt",
    dialCode: "975",
    priority: 0,
    areaCodes: null,
    countryId: 64,
    nationality: "Bhutanese",
    continent: "Asia",
  },
  {
    name: "Bolivia",
    iso2: "bo",
    dialCode: "591",
    priority: 0,
    areaCodes: null,
    countryId: 68,
    nationality: "Bolivian",
    continent: "South America",
  },
  {
    name: "Bosnia and Herzegovina (Босна и Херцеговина)",
    iso2: "ba",
    dialCode: "387",
    priority: 0,
    areaCodes: null,
    countryId: 70,
    nationality: "of Bosnia and Herzegovina",
    continent: "Europe",
  },
  {
    name: "Botswana",
    iso2: "bw",
    dialCode: "267",
    priority: 0,
    areaCodes: null,
    countryId: 72,
    nationality: "Botswanan",
    continent: "Africa",
  },
  {
    name: "Brazil (Brasil)",
    iso2: "br",
    dialCode: "55",
    priority: 0,
    areaCodes: null,
    countryId: 76,
    nationality: "Brazilian",
    continent: "South America",
  },
  {
    name: "British Indian Ocean Territory",
    iso2: "io",
    dialCode: "246",
    priority: 0,
    areaCodes: null,
    countryId: 86,
    nationality: "of the British Indian Ocean Territory",
  },
  {
    name: "British Virgin Islands",
    iso2: "vg",
    dialCode: "1284",
    priority: 0,
    areaCodes: null,
    countryId: 92,
    nationality: "of the British Virgin Islands",
    continent: "North America",
  },
  {
    name: "Brunei",
    iso2: "bn",
    dialCode: "673",
    priority: 0,
    areaCodes: null,
    countryId: 96,
    nationality: "Bruneian",
    continent: "Asia",
  },
  {
    name: "Bulgaria (България)",
    iso2: "bg",
    dialCode: "359",
    priority: 0,
    areaCodes: null,
    countryId: 100,
    nationality: "Bulgarian",
    continent: "Europe",
  },
  {
    name: "Burkina Faso",
    iso2: "bf",
    dialCode: "226",
    priority: 0,
    areaCodes: null,
    countryId: 854,
    nationality: "Burkinabe",
    continent: "Africa",
  },
  {
    name: "Burundi (Uburundi)",
    iso2: "bi",
    dialCode: "257",
    priority: 0,
    areaCodes: null,
    countryId: 108,
    nationality: "Burundian",
    continent: "Africa",
  },
  {
    name: "Cambodia (កម្ពុជា)",
    iso2: "kh",
    dialCode: "855",
    priority: 0,
    areaCodes: null,
    countryId: 116,
    nationality: "Cambodian",
    continent: "Asia",
  },
  {
    name: "Cameroon (Cameroun)",
    iso2: "cm",
    dialCode: "237",
    priority: 0,
    areaCodes: null,
    countryId: 120,
    nationality: "Cameroonian",
    continent: "Africa",
  },
  {
    name: "Canada",
    iso2: "ca",
    dialCode: "1",
    priority: 1,
    areaCodes: [
      "204",
      "226",
      "236",
      "249",
      "250",
      "289",
      "306",
      "343",
      "365",
      "387",
      "403",
      "416",
      "418",
      "431",
      "437",
      "438",
      "450",
      "506",
      "514",
      "519",
      "548",
      "579",
      "581",
      "587",
      "604",
      "613",
      "639",
      "647",
      "672",
      "705",
      "709",
      "742",
      "778",
      "780",
      "782",
      "807",
      "819",
      "825",
      "867",
      "873",
      "902",
      "905",
    ],
    countryId: 124,
    nationality: "Canadian",
    continent: "North America",
  },
  {
    name: "Cape Verde (Kabu Verdi)",
    iso2: "cv",
    dialCode: "238",
    priority: 0,
    areaCodes: null,
    countryId: 132,
    nationality: "Cape Verdean",
    continent: "Africa",
  },
  {
    name: "Caribbean Netherlands",
    iso2: "bq",
    dialCode: "599",
    priority: 1,
    areaCodes: null,
    countryId: 535,
    nationality: "Dutch (Bonaire, Sint Eustatius and Saba)",
    continent: "North America",
  },
  {
    name: "Cayman Islands",
    iso2: "ky",
    dialCode: "1345",
    priority: 0,
    areaCodes: null,
    countryId: 136,
    nationality: "Caymanian",
    continent: "North America",
  },
  {
    name: "Central African Republic (République centrafricaine)",
    iso2: "cf",
    dialCode: "236",
    priority: 0,
    areaCodes: null,
    countryId: 140,
    nationality: "Central African",
    continent: "Africa",
  },
  {
    name: "Chad (Tchad)",
    iso2: "td",
    dialCode: "235",
    priority: 0,
    areaCodes: null,
    countryId: 148,
    nationality: "Chadian",
    continent: "Africa",
  },
  {
    name: "Chile",
    iso2: "cl",
    dialCode: "56",
    priority: 0,
    areaCodes: null,
    countryId: 152,
    nationality: "Chilean",
    continent: "South America",
  },
  {
    name: "China (中国)",
    iso2: "cn",
    dialCode: "86",
    priority: 0,
    areaCodes: null,
    countryId: 156,
    nationality: "Chinese",
    continent: "Asia",
  },
  {
    name: "Christmas Island",
    iso2: "cx",
    dialCode: "61",
    priority: 2,
    areaCodes: null,
    countryId: 162,
    nationality: "of Christmas Island",
    continent: "Asia",
  },
  {
    name: "Cocos (Keeling) Islands",
    iso2: "cc",
    dialCode: "61",
    priority: 1,
    areaCodes: null,
    countryId: 166,
    nationality: "of the Cocos (Keeling) Islands",
    continent: "Asia",
  },
  {
    name: "Colombia",
    iso2: "co",
    dialCode: "57",
    priority: 0,
    areaCodes: null,
    countryId: 170,
    nationality: "Colombian",
    continent: "South America",
  },
  {
    name: "Comoros (‫جزر القمر‬‎)",
    iso2: "km",
    dialCode: "269",
    priority: 0,
    areaCodes: null,
    countryId: 174,
    nationality: "Comorian",
    continent: "Africa",
  },
  {
    name: "Congo (DRC) (Jamhuri ya Kidemokrasia ya Kongo)",
    iso2: "cd",
    dialCode: "243",
    priority: 0,
    areaCodes: null,
    countryId: 180,
    nationality: "Congolese",
    continent: "Africa",
  },
  {
    name: "Congo (Republic) (Congo-Brazzaville)",
    iso2: "cg",
    dialCode: "242",
    priority: 0,
    areaCodes: null,
    countryId: 178,
    nationality: "Congolese",
    continent: "Africa",
  },
  {
    name: "Cook Islands",
    iso2: "ck",
    dialCode: "682",
    priority: 0,
    areaCodes: null,
    countryId: 184,
    nationality: "of the Cook Islands",
    continent: "Oceania",
  },
  {
    name: "Costa Rica",
    iso2: "cr",
    dialCode: "506",
    priority: 0,
    areaCodes: null,
    countryId: 188,
    nationality: "Costa Rican",
    continent: "North America",
  },
  {
    name: "Côte d’Ivoire",
    iso2: "ci",
    dialCode: "225",
    priority: 0,
    areaCodes: null,
    countryId: 384,
    nationality: "Ivorian",
    continent: "Africa",
  },
  {
    name: "Croatia (Hrvatska)",
    iso2: "hr",
    dialCode: "385",
    priority: 0,
    areaCodes: null,
    countryId: 191,
    nationality: "Croatian",
    continent: "Europe",
  },
  {
    name: "Cuba",
    iso2: "cu",
    dialCode: "53",
    priority: 0,
    areaCodes: null,
    countryId: 192,
    nationality: "Cuban",
    continent: "North America",
  },
  {
    name: "Curaçao",
    iso2: "cw",
    dialCode: "599",
    priority: 0,
    areaCodes: null,
    countryId: 531,
    nationality: "Dutch (Curaçao)",
    continent: "North America",
  },
  {
    name: "Cyprus (Κύπρος)",
    iso2: "cy",
    dialCode: "357",
    priority: 0,
    areaCodes: null,
    countryId: 196,
    nationality: "Cypriot",
    continent: "Europe",
  },
  {
    name: "Czech Republic (Česká republika)",
    iso2: "cz",
    dialCode: "420",
    priority: 0,
    areaCodes: null,
    countryId: 203,
    nationality: "Czech",
    continent: "Europe",
  },
  {
    name: "Denmark (Danmark)",
    iso2: "dk",
    dialCode: "45",
    priority: 0,
    areaCodes: null,
    countryId: 208,
    nationality: "Danish",
    continent: "Europe",
  },
  {
    name: "Djibouti",
    iso2: "dj",
    dialCode: "253",
    priority: 0,
    areaCodes: null,
    countryId: 262,
    nationality: "of Djibouti",
    continent: "Africa",
  },
  {
    name: "Dominica",
    iso2: "dm",
    dialCode: "1767",
    priority: 0,
    areaCodes: null,
    countryId: 212,
    nationality: "of Dominica",
    continent: "North America",
  },
  {
    name: "Dominican Republic (República Dominicana)",
    iso2: "do",
    dialCode: "1",
    priority: 2,
    areaCodes: ["809", "829", "849"],
    countryId: 214,
    nationality: "Dominican",
    continent: "North America",
  },
  {
    name: "Ecuador",
    iso2: "ec",
    dialCode: "593",
    priority: 0,
    areaCodes: null,
    countryId: 218,
    nationality: "Ecuadorian",
    continent: "South America",
  },
  {
    name: "Egypt (‫مصر‬‎)",
    iso2: "eg",
    dialCode: "20",
    priority: 0,
    areaCodes: null,
    countryId: 818,
    nationality: "Egyptian",
    continent: "Africa",
  },
  {
    name: "El Salvador",
    iso2: "sv",
    dialCode: "503",
    priority: 0,
    areaCodes: null,
    countryId: 222,
    nationality: "Salvadorian",
    continent: "North America",
  },
  {
    name: "Equatorial Guinea (Guinea Ecuatorial)",
    iso2: "gq",
    dialCode: "240",
    priority: 0,
    areaCodes: null,
    countryId: 226,
    nationality: "of Equatorial Guinea",
    continent: "Africa",
  },
  {
    name: "Eritrea",
    iso2: "er",
    dialCode: "291",
    priority: 0,
    areaCodes: null,
    countryId: 232,
    nationality: "Eritrean",
    continent: "Africa",
  },
  {
    name: "Estonia (Eesti)",
    iso2: "ee",
    dialCode: "372",
    priority: 0,
    areaCodes: null,
    countryId: 233,
    nationality: "Estonian",
    continent: "Europe",
  },
  {
    name: "Ethiopia",
    iso2: "et",
    dialCode: "251",
    priority: 0,
    areaCodes: null,
    countryId: 231,
    nationality: "Ethiopian",
    continent: "Africa",
  },
  {
    name: "Falkland Islands (Islas Malvinas)",
    iso2: "fk",
    dialCode: "500",
    priority: 0,
    areaCodes: null,
    countryId: 238,
    nationality: "of the Falkland Islands",
    continent: "South America",
  },
  {
    name: "Faroe Islands (Føroyar)",
    iso2: "fo",
    dialCode: "298",
    priority: 0,
    areaCodes: null,
    countryId: 234,
    nationality: "Faeroese",
    continent: "Europe",
  },
  {
    name: "Fiji",
    iso2: "fj",
    dialCode: "679",
    priority: 0,
    areaCodes: null,
    countryId: 242,
    nationality: "of Fiji",
    continent: "Oceania",
  },
  {
    name: "Finland (Suomi)",
    iso2: "fi",
    dialCode: "358",
    priority: 0,
    areaCodes: null,
    countryId: 246,
    nationality: "Finnish",
    continent: "Europe",
  },
  {
    name: "France",
    iso2: "fr",
    dialCode: "33",
    priority: 0,
    areaCodes: null,
    countryId: 250,
    nationality: "French",
    continent: "Europe",
  },
  {
    name: "French Guiana (Guyane française)",
    iso2: "gf",
    dialCode: "594",
    priority: 0,
    areaCodes: null,
    countryId: 254,
    nationality: "Guianese",
    continent: "Europe",
  },
  {
    name: "French Polynesia (Polynésie française)",
    iso2: "pf",
    dialCode: "689",
    priority: 0,
    areaCodes: null,
    countryId: 258,
    nationality: "Polynesian",
    continent: "Europe",
  },
  {
    name: "Gabon",
    iso2: "ga",
    dialCode: "241",
    priority: 0,
    areaCodes: null,
    countryId: 266,
    nationality: "Gabonese",
    continent: "Africa",
  },
  {
    name: "Gambia",
    iso2: "gm",
    dialCode: "220",
    priority: 0,
    areaCodes: null,
    countryId: 270,
    nationality: "Gambian",
    continent: "Africa",
  },
  {
    name: "Georgia (საქართველო)",
    iso2: "ge",
    dialCode: "995",
    priority: 0,
    areaCodes: null,
    countryId: 268,
    nationality: "Georgian",
    continent: "Asia",
  },
  {
    name: "Germany (Deutschland)",
    iso2: "de",
    dialCode: "49",
    priority: 0,
    areaCodes: null,
    countryId: 276,
    nationality: "German",
    continent: "Europe",
  },
  {
    name: "Ghana (Gaana)",
    iso2: "gh",
    dialCode: "233",
    priority: 0,
    areaCodes: null,
    countryId: 288,
    nationality: "Ghanaian",
    continent: "Africa",
  },
  {
    name: "Gibraltar",
    iso2: "gi",
    dialCode: "350",
    priority: 0,
    areaCodes: null,
    countryId: 292,
    nationality: "Gibraltarian",
    continent: "Europe",
  },
  {
    name: "Greece (Ελλάδα)",
    iso2: "gr",
    dialCode: "30",
    priority: 0,
    areaCodes: null,
    countryId: 300,
    nationality: "Greek",
    continent: "Europe",
  },
  {
    name: "Greenland (Kalaallit Nunaat)",
    iso2: "gl",
    dialCode: "299",
    priority: 0,
    areaCodes: null,
    countryId: 304,
    nationality: "Greenlandic",
    continent: "North America",
  },
  {
    name: "Grenada",
    iso2: "gd",
    dialCode: "1473",
    priority: 0,
    areaCodes: null,
    countryId: 308,
    nationality: "Grenadian",
    continent: "North America",
  },
  {
    name: "Guadeloupe",
    iso2: "gp",
    dialCode: "590",
    priority: 0,
    areaCodes: null,
    countryId: 312,
    nationality: "Guadeloupean",
    continent: "North America",
  },
  {
    name: "Guam",
    iso2: "gu",
    dialCode: "1671",
    priority: 0,
    areaCodes: null,
    countryId: 316,
    nationality: "Guamanian",
    continent: "Oceania",
  },
  {
    name: "Guatemala",
    iso2: "gt",
    dialCode: "502",
    priority: 0,
    areaCodes: null,
    countryId: 320,
    nationality: "Guatemalan",
    continent: "North America",
  },
  {
    name: "Guernsey",
    iso2: "gg",
    dialCode: "44",
    priority: 1,
    areaCodes: null,
    countryId: 831,
    nationality: "British (Guernsey)",
    continent: "Europe",
  },
  {
    name: "Guinea (Guinée)",
    iso2: "gn",
    dialCode: "224",
    priority: 0,
    areaCodes: null,
    countryId: 324,
    nationality: "Guinean",
    continent: "Africa",
  },
  {
    name: "Guinea-Bissau (Guiné Bissau)",
    iso2: "gw",
    dialCode: "245",
    priority: 0,
    areaCodes: null,
    countryId: 624,
    nationality: "of Guinea-Bissau",
    continent: "Africa",
  },
  {
    name: "Guyana",
    iso2: "gy",
    dialCode: "592",
    priority: 0,
    areaCodes: null,
    countryId: 328,
    nationality: "Guyanese",
    continent: "South America",
  },
  {
    name: "Haiti",
    iso2: "ht",
    dialCode: "509",
    priority: 0,
    areaCodes: null,
    countryId: 332,
    nationality: "Haitian",
    continent: "North America",
  },
  {
    name: "Honduras",
    iso2: "hn",
    dialCode: "504",
    priority: 0,
    areaCodes: null,
    countryId: 340,
    nationality: "Honduran",
    continent: "North America",
  },
  {
    name: "Hong Kong (香港)",
    iso2: "hk",
    dialCode: "852",
    priority: 0,
    areaCodes: null,
    countryId: 344,
    nationality: "Hong Kong Chinese",
    continent: "Asia",
  },
  {
    name: "Hungary (Magyarország)",
    iso2: "hu",
    dialCode: "36",
    priority: 0,
    areaCodes: null,
    countryId: 348,
    nationality: "Hungarian",
    continent: "Europe",
  },
  {
    name: "Iceland (Ísland)",
    iso2: "is",
    dialCode: "354",
    priority: 0,
    areaCodes: null,
    countryId: 352,
    nationality: "Icelandic",
    continent: "Europe",
  },
  {
    name: "India (भारत)",
    iso2: "in",
    dialCode: "91",
    priority: 0,
    areaCodes: null,
    countryId: 356,
    nationality: "Indian",
    continent: "Asia",
  },
  {
    name: "Indonesia",
    iso2: "id",
    dialCode: "62",
    priority: 0,
    areaCodes: null,
    countryId: 360,
    nationality: "Indonesian",
    continent: "Asia",
  },
  {
    name: "Iran (‫ایران‬‎)",
    iso2: "ir",
    dialCode: "98",
    priority: 0,
    areaCodes: null,
    countryId: 364,
    nationality: "Iranian",
    continent: "Asia",
  },
  {
    name: "Iraq (‫العراق‬‎)",
    iso2: "iq",
    dialCode: "964",
    priority: 0,
    areaCodes: null,
    countryId: 368,
    nationality: "Iraqi",
    continent: "Asia",
  },
  {
    name: "Ireland",
    iso2: "ie",
    dialCode: "353",
    priority: 0,
    areaCodes: null,
    countryId: 372,
    nationality: "Irish",
    continent: "Europe",
  },
  {
    name: "Isle of Man",
    iso2: "im",
    dialCode: "44",
    priority: 2,
    areaCodes: null,
    countryId: 833,
    nationality: "British (Isle of Man)",
    continent: "Europe",
  },
  {
    name: "Israel (‫ישראל‬‎)",
    iso2: "il",
    dialCode: "972",
    priority: 0,
    areaCodes: null,
    countryId: 376,
    nationality: "Israeli",
    continent: "Asia",
  },
  {
    name: "Italy (Italia)",
    iso2: "it",
    dialCode: "39",
    priority: 0,
    areaCodes: null,
    countryId: 380,
    nationality: "Italian",
    continent: "Europe",
  },
  {
    name: "Jamaica",
    iso2: "jm",
    dialCode: "1876",
    priority: 0,
    areaCodes: null,
    countryId: 388,
    nationality: "Jamaican",
    continent: "North America",
  },
  {
    name: "Japan (日本)",
    iso2: "jp",
    dialCode: "81",
    priority: 0,
    areaCodes: null,
    countryId: 392,
    nationality: "Japanese",
    continent: "Asia",
  },
  {
    name: "Jersey",
    iso2: "je",
    dialCode: "44",
    priority: 3,
    areaCodes: null,
    countryId: 832,
    nationality: "British (Jersey)",
    continent: "Europe",
  },
  {
    name: "Jordan (‫الأردن‬‎)",
    iso2: "jo",
    dialCode: "962",
    priority: 0,
    areaCodes: null,
    countryId: 400,
    nationality: "Jordanian",
    continent: "Asia",
  },
  {
    name: "Kazakhstan (Казахстан)",
    iso2: "kz",
    dialCode: "77",
    priority: 1,
    areaCodes: null,
    countryId: 398,
    nationality: "Kazakh",
    continent: "Asia",
  },
  {
    name: "Kenya",
    iso2: "ke",
    dialCode: "254",
    priority: 0,
    areaCodes: null,
    countryId: 404,
    nationality: "Kenyan",
    continent: "Africa",
  },
  {
    name: "Kiribati",
    iso2: "ki",
    dialCode: "686",
    priority: 0,
    areaCodes: null,
    countryId: 296,
    nationality: "Kiribatian",
    continent: "Oceania",
  },
  {
    name: "Kuwait (‫الكويت‬‎)",
    iso2: "kw",
    dialCode: "965",
    priority: 0,
    areaCodes: null,
    countryId: 414,
    nationality: "Kuwaiti",
    continent: "Asia",
  },
  {
    name: "Kyrgyzstan (Кыргызстан)",
    iso2: "kg",
    dialCode: "996",
    priority: 0,
    areaCodes: null,
    countryId: 417,
    nationality: "Kyrgyz",
    continent: "Asia",
  },
  {
    name: "Laos (ລາວ)",
    iso2: "la",
    dialCode: "856",
    priority: 0,
    areaCodes: null,
    countryId: 418,
    nationality: "Lao",
    continent: "Asia",
  },
  {
    name: "Latvia (Latvija)",
    iso2: "lv",
    dialCode: "371",
    priority: 0,
    areaCodes: null,
    countryId: 428,
    nationality: "Latvian",
    continent: "Europe",
  },
  {
    name: "Lebanon (‫لبنان‬‎)",
    iso2: "lb",
    dialCode: "961",
    priority: 0,
    areaCodes: null,
    countryId: 422,
    nationality: "Lebanese",
    continent: "Asia",
  },
  {
    name: "Lesotho",
    iso2: "ls",
    dialCode: "266",
    priority: 0,
    areaCodes: null,
    countryId: 426,
    nationality: "of Lesotho",
    continent: "Africa",
  },
  {
    name: "Liberia",
    iso2: "lr",
    dialCode: "231",
    priority: 0,
    areaCodes: null,
    countryId: 430,
    nationality: "Liberian",
    continent: "Africa",
  },
  {
    name: "Libya (‫ليبيا‬‎)",
    iso2: "ly",
    dialCode: "218",
    priority: 0,
    areaCodes: null,
    countryId: 434,
    nationality: "Libyan",
    continent: "Africa",
  },
  {
    name: "Liechtenstein",
    iso2: "li",
    dialCode: "423",
    priority: 0,
    areaCodes: null,
    countryId: 438,
    nationality: "of Liechtenstein",
    continent: "Europe",
  },
  {
    name: "Lithuania (Lietuva)",
    iso2: "lt",
    dialCode: "370",
    priority: 0,
    areaCodes: null,
    countryId: 440,
    nationality: "Lithuanian",
    continent: "Europe",
  },
  {
    name: "Luxembourg",
    iso2: "lu",
    dialCode: "352",
    priority: 0,
    areaCodes: null,
    countryId: 442,
    nationality: "Luxembourgish",
    continent: "Europe",
  },
  {
    name: "Macau (澳門)",
    iso2: "mo",
    dialCode: "853",
    priority: 0,
    areaCodes: null,
    countryId: 446,
    nationality: "Macanese",
    continent: "Asia",
  },
  {
    name: "Macedonia (FYROM) (Македонија)",
    iso2: "mk",
    dialCode: "389",
    priority: 0,
    areaCodes: null,
    countryId: 807,
    nationality: "of Macedonia",
    continent: "Europe",
  },
  {
    name: "Madagascar (Madagasikara)",
    iso2: "mg",
    dialCode: "261",
    priority: 0,
    areaCodes: null,
    countryId: 450,
    nationality: "Malagasy",
    continent: "Africa",
  },
  {
    name: "Malawi",
    iso2: "mw",
    dialCode: "265",
    priority: 0,
    areaCodes: null,
    countryId: 454,
    nationality: "Malawian",
    continent: "Africa",
  },
  {
    name: "Malaysia",
    iso2: "my",
    dialCode: "60",
    priority: 0,
    areaCodes: null,
    countryId: 458,
    nationality: "Malaysian",
    continent: "Asia",
  },
  {
    name: "Maldives",
    iso2: "mv",
    dialCode: "960",
    priority: 0,
    areaCodes: null,
    countryId: 462,
    nationality: "Maldivian",
    continent: "Asia",
  },
  {
    name: "Mali",
    iso2: "ml",
    dialCode: "223",
    priority: 0,
    areaCodes: null,
    countryId: 466,
    nationality: "Malian",
    continent: "Africa",
  },
  {
    name: "Malta",
    iso2: "mt",
    dialCode: "356",
    priority: 0,
    areaCodes: null,
    countryId: 470,
    nationality: "Maltese",
    continent: "Europe",
  },
  {
    name: "Marshall Islands",
    iso2: "mh",
    dialCode: "692",
    priority: 0,
    areaCodes: null,
    countryId: 584,
    nationality: "Marshallese",
    continent: "Oceania",
  },
  {
    name: "Martinique",
    iso2: "mq",
    dialCode: "596",
    priority: 0,
    areaCodes: null,
    countryId: 474,
    nationality: "Martinican",
    continent: "North America",
  },
  {
    name: "Mauritania (‫موريتانيا‬‎)",
    iso2: "mr",
    dialCode: "222",
    priority: 0,
    areaCodes: null,
    countryId: 478,
    nationality: "Mauritanian",
    continent: "Africa",
  },
  {
    name: "Mauritius (Moris)",
    iso2: "mu",
    dialCode: "230",
    priority: 0,
    areaCodes: null,
    countryId: 480,
    nationality: "Mauritian",
    continent: "Africa",
  },
  {
    name: "Mayotte",
    iso2: "yt",
    dialCode: "262",
    priority: 1,
    areaCodes: null,
    countryId: 175,
    nationality: "Mahoran",
    continent: "Africa",
  },
  {
    name: "Mexico (México)",
    iso2: "mx",
    dialCode: "52",
    priority: 0,
    areaCodes: null,
    countryId: 484,
    nationality: "Mexican",
    continent: "North America",
  },
  {
    name: "Micronesia",
    iso2: "fm",
    dialCode: "691",
    priority: 0,
    areaCodes: null,
    countryId: 583,
    nationality: "of Micronesia",
    continent: "Oceania",
  },
  {
    name: "Moldova (Republica Moldova)",
    iso2: "md",
    dialCode: "373",
    priority: 0,
    areaCodes: null,
    countryId: 498,
    nationality: "Moldovan",
    continent: "Europe",
  },
  {
    name: "Monaco",
    iso2: "mc",
    dialCode: "377",
    priority: 0,
    areaCodes: null,
    countryId: 492,
    nationality: "Monegasque",
    continent: "Europe",
  },
  {
    name: "Mongolia (Монгол)",
    iso2: "mn",
    dialCode: "976",
    priority: 0,
    areaCodes: null,
    countryId: 496,
    nationality: "Mongolian",
    continent: "Asia",
  },
  {
    name: "Montenegro (Crna Gora)",
    iso2: "me",
    dialCode: "382",
    priority: 0,
    areaCodes: null,
    countryId: 499,
    nationality: "Montenegran",
    continent: "Europe",
  },
  {
    name: "Montserrat",
    iso2: "ms",
    dialCode: "1664",
    priority: 0,
    areaCodes: null,
    countryId: 500,
    nationality: "Montserratian",
    continent: "North America",
  },
  {
    name: "Morocco (‫المغرب‬‎)",
    iso2: "ma",
    dialCode: "212",
    priority: 0,
    areaCodes: null,
    countryId: 504,
    nationality: "Moroccan",
    continent: "Africa",
  },
  {
    name: "Mozambique (Moçambique)",
    iso2: "mz",
    dialCode: "258",
    priority: 0,
    areaCodes: null,
    countryId: 508,
    nationality: "Mozambican",
    continent: "Africa",
  },
  {
    name: "Myanmar (Burma)",
    iso2: "mm",
    dialCode: "95",
    priority: 0,
    areaCodes: null,
    countryId: 104,
    nationality: "Burmese; of Myanmar",
    continent: "Asia",
  },
  {
    name: "Namibia (Namibië)",
    iso2: "na",
    dialCode: "264",
    priority: 0,
    areaCodes: null,
    countryId: 516,
    nationality: "Namibian",
    continent: "Africa",
  },
  {
    name: "Nauru",
    iso2: "nr",
    dialCode: "674",
    priority: 0,
    areaCodes: null,
    countryId: 520,
    nationality: "Nauruan",
    continent: "Oceania",
  },
  {
    name: "Nepal (नेपाल)",
    iso2: "np",
    dialCode: "977",
    priority: 0,
    areaCodes: null,
    countryId: 524,
    nationality: "Nepalese",
    continent: "Asia",
  },
  {
    name: "Netherlands (Nederland)",
    iso2: "nl",
    dialCode: "31",
    priority: 0,
    areaCodes: null,
    countryId: 528,
    nationality: "Dutch",
    continent: "Europe",
  },
  {
    name: "New Caledonia (Nouvelle-Calédonie)",
    iso2: "nc",
    dialCode: "687",
    priority: 0,
    areaCodes: null,
    countryId: 540,
    nationality: "New Caledonian",
    continent: "Oceania",
  },
  {
    name: "New Zealand",
    iso2: "nz",
    dialCode: "64",
    priority: 0,
    areaCodes: null,
    countryId: 554,
    nationality: "of New Zealand",
    continent: "Oceania",
  },
  {
    name: "Nicaragua",
    iso2: "ni",
    dialCode: "505",
    priority: 0,
    areaCodes: null,
    countryId: 558,
    nationality: "Nicaraguan",
    continent: "North America",
  },
  {
    name: "Niger (Nijar)",
    iso2: "ne",
    dialCode: "227",
    priority: 0,
    areaCodes: null,
    countryId: 562,
    nationality: "Nigerien",
    continent: "Africa",
  },
  {
    name: "Nigeria",
    iso2: "ng",
    dialCode: "234",
    priority: 0,
    areaCodes: null,
    countryId: 566,
    nationality: "Nigerian",
    continent: "Africa",
  },
  {
    name: "Niue",
    iso2: "nu",
    dialCode: "683",
    priority: 0,
    areaCodes: null,
    countryId: 570,
    nationality: "Niuean",
    continent: "Oceania",
  },
  {
    name: "Norfolk Island",
    iso2: "nf",
    dialCode: "672",
    priority: 0,
    areaCodes: null,
    countryId: 574,
    nationality: "of Norfolk Island",
    continent: "Oceania",
  },
  {
    name: "North Korea (조선 민주주의 인민 공화국)",
    iso2: "kp",
    dialCode: "850",
    priority: 0,
    areaCodes: null,
    countryId: 408,
    nationality: "North Korean",
    continent: "Asia",
  },
  {
    name: "Northern Mariana Islands",
    iso2: "mp",
    dialCode: "1670",
    priority: 0,
    areaCodes: null,
    countryId: 580,
    nationality: "of the Northern Mariana Islands",
    continent: "Oceania",
  },
  {
    name: "Norway (Norge)",
    iso2: "no",
    dialCode: "47",
    priority: 0,
    areaCodes: null,
    countryId: 578,
    nationality: "Norwegian",
    continent: "Europe",
  },
  {
    name: "Oman (‫عُمان‬‎)",
    iso2: "om",
    dialCode: "968",
    priority: 0,
    areaCodes: null,
    countryId: 512,
    nationality: "Omani",
    continent: "Asia",
  },
  {
    name: "Pakistan (‫پاکستان‬‎)",
    iso2: "pk",
    dialCode: "92",
    priority: 0,
    areaCodes: null,
    countryId: 586,
    nationality: "Pakistani",
    continent: "Asia",
  },
  {
    name: "Palau",
    iso2: "pw",
    dialCode: "680",
    priority: 0,
    areaCodes: null,
    countryId: 585,
    nationality: "Palauan",
    continent: "Oceania",
  },
  {
    name: "Palestine (‫فلسطين‬‎)",
    iso2: "ps",
    dialCode: "970",
    priority: 0,
    areaCodes: null,
    countryId: 275,
    nationality: "Palestinian",
    continent: "Asia",
  },
  {
    name: "Panama (Panamá)",
    iso2: "pa",
    dialCode: "507",
    priority: 0,
    areaCodes: null,
    countryId: 591,
    nationality: "Panamanian",
    continent: "North America",
  },
  {
    name: "Papua New Guinea",
    iso2: "pg",
    dialCode: "675",
    priority: 0,
    areaCodes: null,
    countryId: 598,
    nationality: "of Papua New Guinea",
    continent: "Oceania",
  },
  {
    name: "Paraguay",
    iso2: "py",
    dialCode: "595",
    priority: 0,
    areaCodes: null,
    countryId: 600,
    nationality: "Paraguayan",
    continent: "South America",
  },
  {
    name: "Peru (Perú)",
    iso2: "pe",
    dialCode: "51",
    priority: 0,
    areaCodes: null,
    countryId: 604,
    nationality: "Peruvian",
    continent: "South America",
  },
  {
    name: "Philippines",
    iso2: "ph",
    dialCode: "63",
    priority: 0,
    areaCodes: null,
    countryId: 608,
    nationality: "Philippine",
    continent: "Asia",
  },
  {
    name: "Poland (Polska)",
    iso2: "pl",
    dialCode: "48",
    priority: 0,
    areaCodes: null,
    countryId: 616,
    nationality: "Polish",
    continent: "Europe",
  },
  {
    name: "Portugal",
    iso2: "pt",
    dialCode: "351",
    priority: 0,
    areaCodes: null,
    countryId: 620,
    nationality: "Portuguese",
    continent: "Europe",
  },
  {
    name: "Puerto Rico",
    iso2: "pr",
    dialCode: "1",
    priority: 3,
    areaCodes: ["787", "939"],
    countryId: 630,
    nationality: "Puerto Rican",
    continent: "North America",
  },
  {
    name: "Qatar (‫قطر‬‎)",
    iso2: "qa",
    dialCode: "974",
    priority: 0,
    areaCodes: null,
    countryId: 634,
    nationality: "Qatari",
    continent: "Asia",
  },
  {
    name: "Réunion (La Réunion)",
    iso2: "re",
    dialCode: "262",
    priority: 0,
    areaCodes: null,
    countryId: 638,
    nationality: "Reunionese",
    continent: "Africa",
  },
  {
    name: "Romania (România)",
    iso2: "ro",
    dialCode: "40",
    priority: 0,
    areaCodes: null,
    countryId: 642,
    nationality: "Romanian",
    continent: "Europe",
  },
  {
    name: "Russia (Россия)",
    iso2: "ru",
    dialCode: "7",
    priority: 0,
    areaCodes: null,
    countryId: 643,
    nationality: "Russian",
    continent: "Europe",
  },
  {
    name: "Rwanda",
    iso2: "rw",
    dialCode: "250",
    priority: 0,
    areaCodes: null,
    countryId: 646,
    nationality: "Rwandan",
    continent: "Africa",
  },
  {
    name: "Saint Barthélemy (Saint-Barthélemy)",
    iso2: "bl",
    dialCode: "590",
    priority: 1,
    areaCodes: null,
    countryId: 652,
    nationality: "French (Saint-Barthélemy)",
    continent: "North America",
  },
  {
    name: "Saint Helena",
    iso2: "sh",
    dialCode: "290",
    priority: 0,
    areaCodes: null,
    countryId: 654,
    nationality: "Saint Helenian",
    continent: "Africa",
  },
  {
    name: "Saint Kitts and Nevis",
    iso2: "kn",
    dialCode: "1869",
    priority: 0,
    areaCodes: null,
    countryId: 659,
    nationality: "of Saint Kitts and Nevis",
    continent: "North America",
  },
  {
    name: "Saint Lucia",
    iso2: "lc",
    dialCode: "1758",
    priority: 0,
    areaCodes: null,
    countryId: 662,
    nationality: "Saint Lucian",
    continent: "North America",
  },
  {
    name: "Saint Martin (Saint-Martin (partie française))",
    iso2: "mf",
    dialCode: "590",
    priority: 2,
    areaCodes: null,
    countryId: 663,
    nationality: "of Saint Martin",
    continent: "North America",
  },
  {
    name: "Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)",
    iso2: "pm",
    dialCode: "508",
    priority: 0,
    areaCodes: null,
    countryId: 666,
    nationality: "of Saint Pierre and Miquelon",
    continent: "North America",
  },
  {
    name: "Saint Vincent and the Grenadines",
    iso2: "vc",
    dialCode: "1784",
    priority: 0,
    areaCodes: null,
    countryId: 670,
    nationality: "Vincentian",
    continent: "North America",
  },
  {
    name: "Samoa",
    iso2: "ws",
    dialCode: "685",
    priority: 0,
    areaCodes: null,
    countryId: 882,
    nationality: "Samoan",
    continent: "Oceania",
  },
  {
    name: "San Marino",
    iso2: "sm",
    dialCode: "378",
    priority: 0,
    areaCodes: null,
    countryId: 674,
    nationality: "of San Marino",
    continent: "Europe",
  },
  {
    name: "São Tomé and Príncipe (São Tomé e Príncipe)",
    iso2: "st",
    dialCode: "239",
    priority: 0,
    areaCodes: null,
    countryId: 678,
    nationality: "of Sao Tome and Principe",
    continent: "Africa",
  },
  {
    name: "Saudi Arabia (‫المملكة العربية السعودية‬‎)",
    iso2: "sa",
    dialCode: "966",
    priority: 0,
    areaCodes: null,
    countryId: 682,
    nationality: "Saudi Arabian",
    continent: "Asia",
  },
  {
    name: "Senegal (Sénégal)",
    iso2: "sn",
    dialCode: "221",
    priority: 0,
    areaCodes: null,
    countryId: 686,
    nationality: "Senegalese",
    continent: "Africa",
  },
  {
    name: "Serbia (Србија)",
    iso2: "rs",
    dialCode: "381",
    priority: 0,
    areaCodes: null,
    countryId: 688,
    nationality: "Serbian",
    continent: "Europe",
  },
  {
    name: "Seychelles",
    iso2: "sc",
    dialCode: "248",
    priority: 0,
    areaCodes: null,
    countryId: 690,
    nationality: "of Seychelles",
    continent: "Africa",
  },
  {
    name: "Sierra Leone",
    iso2: "sl",
    dialCode: "232",
    priority: 0,
    areaCodes: null,
    countryId: 694,
    nationality: "Sierra Leonean",
    continent: "Africa",
  },
  {
    name: "Singapore",
    iso2: "sg",
    dialCode: "65",
    priority: 0,
    areaCodes: null,
    countryId: 702,
    nationality: "Singaporean",
    continent: "Asia",
  },
  {
    name: "Sint Maarten",
    iso2: "sx",
    dialCode: "1721",
    priority: 0,
    areaCodes: null,
    countryId: 534,
    nationality: "Dutch (Sint Maarten)",
    continent: "North America",
  },
  {
    name: "Slovakia (Slovensko)",
    iso2: "sk",
    dialCode: "421",
    priority: 0,
    areaCodes: null,
    countryId: 703,
    nationality: "Slovak",
    continent: "Europe",
  },
  {
    name: "Slovenia (Slovenija)",
    iso2: "si",
    dialCode: "386",
    priority: 0,
    areaCodes: null,
    countryId: 705,
    nationality: "Slovenian",
    continent: "Europe",
  },
  {
    name: "Solomon Islands",
    iso2: "sb",
    dialCode: "677",
    priority: 0,
    areaCodes: null,
    countryId: 90,
    nationality: "of the Solomon Islands",
    continent: "Oceania",
  },
  {
    name: "Somalia (Soomaaliya)",
    iso2: "so",
    dialCode: "252",
    priority: 0,
    areaCodes: null,
    countryId: 706,
    nationality: "Somali",
    continent: "Africa",
  },
  {
    name: "South Africa",
    iso2: "za",
    dialCode: "27",
    priority: 0,
    areaCodes: null,
    countryId: 710,
    nationality: "South African",
    continent: "Africa",
  },
  {
    name: "South Korea (대한민국)",
    iso2: "kr",
    dialCode: "82",
    priority: 0,
    areaCodes: null,
    countryId: 410,
    nationality: "South Korean",
    continent: "Asia",
  },
  {
    name: "South Sudan (‫جنوب السودان‬‎)",
    iso2: "ss",
    dialCode: "211",
    priority: 0,
    areaCodes: null,
    countryId: 728,
    nationality: "South Sudanese",
    continent: "Africa",
  },
  {
    name: "Spain (España)",
    iso2: "es",
    dialCode: "34",
    priority: 0,
    areaCodes: null,
    countryId: 724,
    nationality: "Spanish",
    continent: "Europe",
  },
  {
    name: "Sri Lanka (ශ්‍රී ලංකාව)",
    iso2: "lk",
    dialCode: "94",
    priority: 0,
    areaCodes: null,
    countryId: 144,
    nationality: "Sri Lankan",
    continent: "Asia",
  },
  {
    name: "Sudan (‫السودان‬‎)",
    iso2: "sd",
    dialCode: "249",
    priority: 0,
    areaCodes: null,
    countryId: 729,
    nationality: "Sudanese",
    continent: "Africa",
  },
  {
    name: "Suriname",
    iso2: "sr",
    dialCode: "597",
    priority: 0,
    areaCodes: null,
    countryId: 740,
    nationality: "Surinamese",
    continent: "South America",
  },
  {
    name: "Svalbard and Jan Mayen",
    iso2: "sj",
    dialCode: "47",
    priority: 1,
    areaCodes: null,
    countryId: 744,
    nationality: "of Svalbard",
    continent: "Europe",
  },
  {
    name: "Swaziland",
    iso2: "sz",
    dialCode: "268",
    priority: 0,
    areaCodes: null,
    countryId: 748,
    nationality: "Swazi",
    continent: "Africa",
  },
  {
    name: "Sweden (Sverige)",
    iso2: "se",
    dialCode: "46",
    priority: 0,
    areaCodes: null,
    countryId: 752,
    nationality: "Swedish",
    continent: "Europe",
  },
  {
    name: "Switzerland (Schweiz)",
    iso2: "ch",
    dialCode: "41",
    priority: 0,
    areaCodes: null,
    countryId: 756,
    nationality: "Swiss",
    continent: "Europe",
  },
  {
    name: "Syria (‫سوريا‬‎)",
    iso2: "sy",
    dialCode: "963",
    priority: 0,
    areaCodes: null,
    countryId: 760,
    nationality: "Syrian",
    continent: "Asia",
  },
  {
    name: "Taiwan (台灣)",
    iso2: "tw",
    dialCode: "886",
    priority: 0,
    areaCodes: null,
    countryId: 158,
    nationality: "Taiwanese",
    continent: "Asia",
  },
  {
    name: "Tajikistan",
    iso2: "tj",
    dialCode: "992",
    priority: 0,
    areaCodes: null,
    countryId: 762,
    nationality: "Tajik",
    continent: "Asia",
  },
  {
    name: "Tanzania",
    iso2: "tz",
    dialCode: "255",
    priority: 0,
    areaCodes: null,
    countryId: 834,
    nationality: "Tanzanian",
    continent: "Africa",
  },
  {
    name: "Thailand (ไทย)",
    iso2: "th",
    dialCode: "66",
    priority: 0,
    areaCodes: null,
    countryId: 764,
    nationality: "Thai",
    continent: "Asia",
  },
  {
    name: "Timor-Leste",
    iso2: "tl",
    dialCode: "670",
    priority: 0,
    areaCodes: null,
    countryId: 626,
    nationality: "of Timor-Leste",
    continent: "Asia",
  },
  {
    name: "Togo",
    iso2: "tg",
    dialCode: "228",
    priority: 0,
    areaCodes: null,
    countryId: 768,
    nationality: "Togolese",
    continent: "Africa",
  },
  {
    name: "Tokelau",
    iso2: "tk",
    dialCode: "690",
    priority: 0,
    areaCodes: null,
    countryId: 772,
    nationality: "Tokelauan",
    continent: "Oceania",
  },
  {
    name: "Tonga",
    iso2: "to",
    dialCode: "676",
    priority: 0,
    areaCodes: null,
    countryId: 776,
    nationality: "Tongan",
    continent: "Oceania",
  },
  {
    name: "Trinidad and Tobago",
    iso2: "tt",
    dialCode: "1868",
    priority: 0,
    areaCodes: null,
    countryId: 780,
    nationality: "of Trinidad and Tobago",
    continent: "North America",
  },
  {
    name: "Tunisia (‫تونس‬‎)",
    iso2: "tn",
    dialCode: "216",
    priority: 0,
    areaCodes: null,
    countryId: 788,
    nationality: "Tunisian",
    continent: "Africa",
  },
  {
    name: "Turkey (Türkiye)",
    iso2: "tr",
    dialCode: "90",
    priority: 0,
    areaCodes: null,
    countryId: 792,
    nationality: "Turkish",
    continent: "Asia",
  },
  {
    name: "Turkmenistan",
    iso2: "tm",
    dialCode: "993",
    priority: 0,
    areaCodes: null,
    countryId: 795,
    nationality: "Turkmen",
    continent: "Asia",
  },
  {
    name: "Turks and Caicos Islands",
    iso2: "tc",
    dialCode: "1649",
    priority: 0,
    areaCodes: null,
    countryId: 796,
    nationality: "of the Turks and Caicos Islands",
    continent: "North America",
  },
  {
    name: "Tuvalu",
    iso2: "tv",
    dialCode: "688",
    priority: 0,
    areaCodes: null,
    countryId: 798,
    nationality: "Tuvaluan",
    continent: "Oceania",
  },
  {
    name: "U.S. Virgin Islands",
    iso2: "vi",
    dialCode: "1340",
    priority: 0,
    areaCodes: null,
    countryId: 850,
    nationality: "of the US Virgin Islands",
    continent: "North America",
  },
  {
    name: "Uganda",
    iso2: "ug",
    dialCode: "256",
    priority: 0,
    areaCodes: null,
    countryId: 800,
    nationality: "Ugandan",
    continent: "Africa",
  },
  {
    name: "Ukraine (Україна)",
    iso2: "ua",
    dialCode: "380",
    priority: 0,
    areaCodes: null,
    countryId: 804,
    nationality: "Ukrainian",
    continent: "Europe",
  },
  {
    name: "United Arab Emirates (‫الإمارات العربية المتحدة‬‎)",
    iso2: "ae",
    dialCode: "971",
    priority: 0,
    areaCodes: null,
    countryId: 784,
    nationality: "Emirati",
    continent: "Asia",
  },
  {
    name: "United Kingdom",
    iso2: "gb",
    dialCode: "44",
    priority: 0,
    areaCodes: null,
    countryId: 826,
    nationality: "British",
    continent: "Europe",
  },
  {
    name: "United States",
    iso2: "us",
    dialCode: "1",
    priority: 0,
    areaCodes: null,
    countryId: 840,
    nationality: "American",
    continent: "North America",
  },
  {
    name: "Uruguay",
    iso2: "uy",
    dialCode: "598",
    priority: 0,
    areaCodes: null,
    countryId: 858,
    nationality: "Uruguayan",
    continent: "South America",
  },
  {
    name: "Uzbekistan (Oʻzbekiston)",
    iso2: "uz",
    dialCode: "998",
    priority: 0,
    areaCodes: null,
    countryId: 860,
    nationality: "Uzbek",
    continent: "Asia",
  },
  {
    name: "Vanuatu",
    iso2: "vu",
    dialCode: "678",
    priority: 0,
    areaCodes: null,
    countryId: 548,
    nationality: "Vanuatuan",
    continent: "Oceania",
  },
  {
    name: "Vatican City (Città del Vaticano)",
    iso2: "va",
    dialCode: "39",
    priority: 1,
    areaCodes: null,
    countryId: 336,
    nationality: "of the Holy See (of the Vatican)",
    continent: "Europe",
  },
  {
    name: "Venezuela",
    iso2: "ve",
    dialCode: "58",
    priority: 0,
    areaCodes: null,
    countryId: 862,
    nationality: "Venezuelan",
    continent: "South America",
  },
  {
    name: "Vietnam (Việt Nam)",
    iso2: "vn",
    dialCode: "84",
    priority: 0,
    areaCodes: null,
    countryId: 704,
    nationality: "Vietnamese",
    continent: "Asia",
  },
  {
    name: "Wallis and Futuna",
    iso2: "wf",
    dialCode: "681",
    priority: 0,
    areaCodes: null,
    countryId: 876,
    nationality: "of the Wallis and Futuna Islands",
    continent: "Oceania",
  },
  {
    name: "Western Sahara (‫الصحراء الغربية‬‎)",
    iso2: "eh",
    dialCode: "212",
    priority: 1,
    areaCodes: null,
    countryId: 732,
    nationality: "Sahrawi",
    continent: "Africa",
  },
  {
    name: "Yemen (‫اليمن‬‎)",
    iso2: "ye",
    dialCode: "967",
    priority: 0,
    areaCodes: null,
    countryId: 887,
    nationality: "Yemeni",
    continent: "Asia",
  },
  {
    name: "Zambia",
    iso2: "zm",
    dialCode: "260",
    priority: 0,
    areaCodes: null,
    countryId: 894,
    nationality: "Zambian",
    continent: "Africa",
  },
  {
    name: "Zimbabwe",
    iso2: "zw",
    dialCode: "263",
    priority: 0,
    areaCodes: null,
    countryId: 716,
    nationality: "Zimbabwean",
    continent: "Africa",
  },
  {
    name: "Åland Islands",
    iso2: "ax",
    dialCode: "358",
    priority: 1,
    areaCodes: null,
    countryId: 248,
    nationality: "Finnish (Åland Islands)",
    continent: "Europe",
  },
  {
    countryId: 10,
    name: "Antarctica",
    iso2: "aq",
    dialCode: "672",
    priority: 0,
    areaCodes: null,
    nationality: "Antarctic",
    continent: "Other",
  },
  {
    countryId: 74,
    name: "Bouvet Island",
    iso2: "bv",
    dialCode: "47",
    priority: 0,
    areaCodes: null,
    nationality: "of Bouvet Island",
    continent: "Africa",
  },
  {
    countryId: 260,
    name: "French Southern Territories",
    iso2: "tf",
    dialCode: "262",
    priority: 0,
    areaCodes: null,
    nationality: "of the French Southern and Antarctic Lands",
    continent: "Antarctic",
  },
  {
    countryId: 334,
    name: "Heard Island and McDonald Islands",
    iso2: "hm",
    dialCode: "672",
    priority: 0,
    areaCodes: null,
    nationality: "of the Heard Island and McDonald Islands",
    continent: "Antarctic",
  },
  {
    countryId: 612,
    name: "Pitcairn",
    iso2: "pn",
    dialCode: "64",
    priority: 0,
    areaCodes: null,
    nationality: "Pitcairner",
    continent: "Oceania",
  },
  {
    countryId: 239,
    name: "South Georgia and the South Sandwich Islands",
    iso2: "gs",
    dialCode: "500",
    priority: 0,
    areaCodes: null,
    nationality: "of South Georgia and the South Sandwich Islands",
    continent: "Antarctic",
  },
  {
    countryId: 581,
    name: "United States Minor Outlying Islands",
    iso2: "um",
    dialCode: "1",
    priority: 0,
    areaCodes: null,
    nationality: "of United States Minor Outlying Islands",
    continent: "North America",
  },
];
