import { countryDataCodes } from "./countries";
import { USER_TRANSACTION_STATUS, USER_TRANSACTION_TYPES } from "./enums";

export const allowedOperators = ["eq", "ne", "gt", "gte", "lt", "lte"];
export const mappedOperators = {
  eq: "is equal to",
  ne: "is not equal to",
  gt: "is greater than",
  gte: "is greater than or equal to",
  lt: "is less than",
  lte: "is less than or equal to",
};

const filterOptions = Object.freeze({
  CLIENTS: [
    {
      name: "KYC Approved",
      type: "kycStatus",
      operators: ["is"],
      values: ["true", "false"],
      inputType: "select",
    },
    {
      name: "Has Documents",
      type: "hasDocuments",
      operators: ["is"],
      values: ["true", "false"],
      inputType: "select",
    },
    {
      name: "Device Type",
      type: "deviceType",
      operators: ["is"],
      values: [
        { label: "Windows", value: "win" },
        { label: "Android", value: "android" },
        { label: "iOS", value: "iOS" },
      ],
      inputType: "multiselect",
    },
    // {
    //   name: "Live Accounts",
    //   type: "liveAccounts",
    //   operators: allowedOperators,
    //   values: [1, 2, 3, 4, 5, 6, 7, 8],
    //   inputType: "select",
    // },
    // {
    //   name: "Demo Accounts",
    //   type: "demoAccounts",
    //   operators: allowedOperators,
    //   values: [1, 2, 3, 4, 5, 6, 7, 8],
    //   inputType: "select",
    // },
    {
      name: "First Time Deposit Amount (USD)",
      type: "ftdAmount",
      operators: allowedOperators,
      values: [],
      inputType: "number",
    },
    {
      name: "From Date",
      type: "fromDate",
      operators: ["is"],
      values: [],
      inputType: "date",
    },
    {
      name: "To Date",
      type: "toDate",
      operators: ["is"],
      values: [],
      inputType: "date",
    },
    {
      name: "Deposit Amount",
      type: "depositAmount",
      operators: ["gt", "gte", "lt", "lte"],
      values: [
        { value: "100", label: "$100" },
        { value: "1000", label: "$1000" },
        { value: "10000", label: "$10000" },
        { value: "100000", label: "$100000" },
      ],
      inputType: "select",
    },
    {
      name: "Withdrawal Amount",
      type: "withdrawalAmount",
      operators: ["gt", "gte", "lt", "lte"],
      values: [
        { value: "100", label: "$100" },
        { value: "1000", label: "$1000" },
        { value: "10000", label: "$10000" },
        { value: "100000", label: "$100000" },
      ],
      inputType: "select",
    },
    {
      name: "Country",
      type: "country",
      operators: ["is"],
      values: countryDataCodes.map((x) => ({
        value: x.iso2.toUpperCase(),
        label: x.name,
      })),
      inputType: "multiselect",
    },
  ],
  REQUESTS: [
    // Unecessary until more types are added
    // {
    //   name: "Request Type",
    //   type: "requestType",
    //   operators: ["is"],
    //   values: [{ value: "deleteAccount", label: "Delete Account" }],
    //   inputType: "multiselect",
    // },
    {
      name: "From Date",
      type: "fromDate",
      operators: ["is"],
      values: [],
      inputType: "date",
    },
    {
      name: "To Date",
      type: "toDate",
      operators: ["is"],
      values: [],
      inputType: "date",
    },
  ],
  WITHDRAW_REQUESTS: [
    {
      name: "Withdraw Amount",
      type: "withdrawAmount",
      operators: ["gt", "gte", "lt", "lte"],
      values: [],
      inputType: "number",
    },
    {
      name: "Withdraw Currency",
      type: "withdrawCurrency",
      operators: ["is"],
      values: ["USD", "EUR", "GBP", "CAD", "AUD"],
      inputType: "multiselect",
    },
    // {
    //   name: "From Date",
    //   type: "fromDate",
    //   operators: ["is"],
    //   values: [],
    //   inputType: "date",
    // },
    // {
    //   name: "To Date",
    //   type: "toDate",
    //   operators: ["is"],
    //   values: [],
    //   inputType: "date",
    // },
  ],
  APPROVED_WITHDRAWALS: [
    {
      name: "Currency",
      type: "currency",
      operators: ["is"],
      values: ["USD", "EUR", "GBP", "CAD", "AUD"],
      inputType: "multiselect",
    },
    {
      name: "Amount",
      type: "amount",
      operators: ["gt", "gte", "lt", "lte"],
      values: [],
      inputType: "number",
    },
    {
      name: "Amount (USD)",
      type: "amountUSD",
      operators: ["gt", "gte", "lt", "lte"],
      values: [],
      inputType: "number",
    },
    // {
    //   name: "From Date",
    //   type: "fromDate",
    //   operators: ["is"],
    //   values: [],
    //   inputType: "date",
    // },
    // {
    //   name: "To Date",
    //   type: "toDate",
    //   operators: ["is"],
    //   values: [],
    //   inputType: "date",
    // },
  ],
  DEPOSITS: [
    {
      name: "Currency",
      type: "currency",
      operators: ["is"],
      values: ["USD", "EUR", "GBP", "CAD", "AUD"],
      inputType: "multiselect",
    },
    {
      name: "Processed Amount",
      type: "processedAmount",
      operators: ["gt", "gte", "lt", "lte"],
      values: [],
      inputType: "number",
    },
    {
      name: "Processed Amount (USD)",
      type: "processedUsdAmount",
      operators: ["gt", "gte", "lt", "lte"],
      values: [],
      inputType: "number",
    },
    // {
    //   name: "From Date",
    //   type: "fromDate",
    //   operators: ["is"],
    //   values: [],
    //   inputType: "date",
    // },
    // {
    //   name: "To Date",
    //   type: "toDate",
    //   operators: ["is"],
    //   values: [],
    //   inputType: "date",
    // },
  ],
  FINANCES: [
    {
      name: "Currency",
      type: "currency",
      operators: ["is"],
      values: ["USD", "EUR", "GBP", "CAD", "AUD"],
      inputType: "multiselect",
    },
    {
      name: "Processed Amount",
      type: "processedAmount",
      operators: ["gt", "gte", "lt", "lte"],
      values: [],
      inputType: "number",
    },
    {
      name: "Processed Amount (USD)",
      type: "processedUsdAmount",
      operators: ["gt", "gte", "lt", "lte"],
      values: [],
      inputType: "number",
    },
    // {
    //   name: "From Date",
    //   type: "fromDate",
    //   operators: ["is"],
    //   values: [],
    //   inputType: "date",
    // },
    // {
    //   name: "To Date",
    //   type: "toDate",
    //   operators: ["is"],
    //   values: [],
    //   inputType: "date",
    // },
  ],
  USER_FINANCES: [
    {
      name: "Transaction Type",
      type: "transaction_type",
      operators: ["is"],
      values: Object.values(USER_TRANSACTION_TYPES),
      inputType: "multiselect",
    },
    {
      name: "Transaction Status",
      type: "status",
      operators: ["is"],
      values: Array.from(new Set(Object.values(USER_TRANSACTION_STATUS))),
      inputType: "multiselect",
    },
    {
      name: "Currency",
      type: "currency",
      operators: ["is"],
      values: ["USD", "EUR", "GBP", "CAD", "AUD"],
      inputType: "multiselect",
    },
    {
      name: "Processed Amount",
      type: "processedAmount",
      operators: ["gt", "gte", "lt", "lte"],
      values: [],
      inputType: "number",
    },
    {
      name: "Processed Amount (USD)",
      type: "processedUsdAmount",
      operators: ["gt", "gte", "lt", "lte"],
      values: [],
      inputType: "number",
    },
    {
      name: "From Date",
      type: "fromDate",
      operators: ["is"],
      values: [],
      inputType: "date",
    },
    {
      name: "To Date",
      type: "toDate",
      operators: ["is"],
      values: [],
      inputType: "date",
    },
  ],
  LOGS: [
    {
      name: "From Date",
      type: "fromDate",
      operators: ["is"],
      values: [],
      inputType: "date",
    },
    {
      name: "To Date",
      type: "toDate",
      operators: ["is"],
      values: [],
      inputType: "date",
    },
  ],
  UTMS: [
    {
      name: "From Date",
      type: "fromDate",
      operators: ["is"],
      values: [],
      inputType: "date",
    },
    {
      name: "To Date",
      type: "toDate",
      operators: ["is"],
      values: [],
      inputType: "date",
    },
  ],
});

export default filterOptions;
