import { PERMISSIONS } from "./permissions";

const availableFields = {
  CLIENTS: [
    {
      value: "readableId",
      label: "Client ID",
      gridColumnSize: "minmax(100px, 1fr)",
      key: "readableId",
      selected: true,
    },
    {
      value: "userId",
      label: "User ID",
      gridColumnSize: "minmax(200px, 2fr)",
      key: "_id",
    },
    {
      value: "cid",
      label: "CTrader ID",
      sortable: true,
      gridColumnSize: "minmax(130px, 2fr)",
      key: "ctrader_id",
    },
    {
      value: "mt5id",
      key: "mt5_id",
      label: "MT5 ID",
      gridColumnSize: "minmax(120px, 2fr)",
      // selected: true,
    },
    {
      value: "mt4id",
      key: "mt4_id",
      label: "MT4 ID",
      gridColumnSize: "minmax(120px, 2fr)",
      // selected: true,
    },
    {
      value: "entity",
      key: "entity",
      label: "Entity",
      gridColumnSize: "minmax(120px, 2fr)",
      selected: true,
    },
    {
      value: "email",
      label: "Email",
      selected: true,
      sortable: true,
      gridColumnSize: "minmax(300px, 2fr)",
      key: "email",
    },
    {
      value: "phone",
      label: "Phone",
      selected: true,
      gridColumnSize: "minmax(150px, 2fr)",
      key: "phone",
    },
    {
      value: "firstName",
      label: "First Name",
      selected: true,
      sortable: true,
      gridColumnSize: "minmax(170px, 2fr)",
      key: "first_name",
    },
    {
      value: "lastName",
      label: "Last Name",
      selected: true,
      sortable: true,
      gridColumnSize: "minmax(170px, 2fr)",
      key: "last_name",
    },
    {
      value: "country",
      label: "Country",
      selected: true,
      sortable: true,
      gridColumnSize: "minmax(120px, 2fr)",
      key: "country",
    },
    {
      value: "city",
      label: "City",
      gridColumnSize: "minmax(150px, 2fr)",
      key: "city",
    },
    {
      value: "terms",
      label: "Terms",
      gridColumnSize: "minmax(80px, 2fr)",
      key: "terms",
    },
    {
      value: "lastLogin",
      label: "Last Login",
      gridColumnSize: "minmax(150px, 2fr)",
      key: "last_login",
    },
    {
      value: "language",
      label: "Language",
      selected: true,
      sortable: true,
      gridColumnSize: "minmax(130px, 2fr)",
      key: "language",
    },
    {
      value: "deviceType",
      label: "Device Type",
      selected: true,
      sortable: true,
      gridColumnSize: "minmax(140px, 2fr)",
      key: "metadata.deviceType",
    },
    {
      value: "dob",
      label: "Date of Birth",
      gridColumnSize: "minmax(200px, 2fr)",
      key: "date_of_birth",
    },
    {
      value: "salesAgentId",
      label: "Sales Agent ID",
      gridColumnSize: "minmax(200px, 2fr)",
      key: "sales_agent",
    },
    {
      value: "hasDocuments",
      label: "Has Documents",
      gridColumnSize: "minmax(140px, 2fr)",
      key: "flags.hasDocuments",
    },
    {
      value: "kycStatus",
      label: "KYC Status",
      gridColumnSize: "minmax(170px, 2fr)",
      key: "flags.kycStatus",
    },
    {
      value: "createdAt",
      label: "Created At",
      selected: true,
      sortable: true,
      gridColumnSize: "minmax(150px, 2fr)",
      key: "createdAt",
    },
    {
      value: "updatedAt",
      label: "Updated At",
      sortable: true,
      gridColumnSize: "minmax(150px, 2fr)",
      key: "updatedAt",
    },
    // {
    //   value: "demoAccounts",
    //   label: "Demo Accounts",
    //   gridColumnSize: "minmax(150px, 2fr)",
    //   key: "accounts.demo",
    // },
    // {
    //   value: "liveAccounts",
    //   label: "Live Accounts",
    //   gridColumnSize: "minmax(150px, 2fr)",
    //   key: "accounts.live",
    // },
    {
      value: "depositAmount",
      label: "Deposit Amount USD",
      gridColumnSize: "minmax(200px, 2fr)",
      key: "accounts.total_deposits_usd",
    },
    {
      value: "withdrawAmount",
      label: "Withdrawal Amount USD",
      gridColumnSize: "minmax(200px, 2fr)",
      key: "accounts.total_withdrawals_usd",
    },
    {
      value: "firstTimeDeposit",
      label: "First Time Deposit",
      gridColumnSize: "minmax(200px, 2fr)",
      key: "first_time_deposit.amount",
    },
    {
      value: "firstTimeWithdrawal",
      label: "First Time Withdrawal",
      gridColumnSize: "minmax(200px, 2fr)",
      key: "first_time_withdrawal.amount",
    },
  ],
  ACTIVE_TRADERS: [
    {
      value: "readableId",
      label: "Client ID",
      gridColumnSize: "minmax(100px, 1fr)",
      key: "readableId",
      selected: true,
    },
    {
      value: "email",
      label: "Email",
      selected: true,
      sortable: true,
      gridColumnSize: "minmax(300px, 2fr)",
      key: "email",
    },
    {
      value: "firstName",
      label: "First Name",
      selected: true,
      sortable: true,
      gridColumnSize: "minmax(170px, 2fr)",
      key: "first_name",
    },
    {
      value: "lastName",
      label: "Last Name",
      selected: true,
      sortable: true,
      gridColumnSize: "minmax(170px, 2fr)",
      key: "last_name",
    },
    {
      value: "language",
      label: "Language",
      selected: true,
      sortable: true,
      gridColumnSize: "minmax(130px, 1fr)",
      key: "language",
    },
    {
      value: "deviceType",
      label: "Device Type",
      selected: true,
      sortable: true,
      gridColumnSize: "minmax(140px, 1fr)",
      key: "metadata.deviceType",
    },
    {
      value: "updatedAt",
      label: "Updated At",
      selected: true,
      sortable: true,
      gridColumnSize: "minmax(150px, 2fr)",
      key: "updatedAt",
    },
  ],
  REQUESTS: [
    {
      value: "requestId",
      key: "_id",
      label: "Request ID",
      gridColumnSize: "minmax(200px, 2fr)",
    },
    {
      value: "userId",
      key: "user._id",
      label: "User ID",
      gridColumnSize: "minmax(200px, 2fr)",
    },
    {
      value: "userReadableId",
      label: "Client ID",
      gridColumnSize: "minmax(100px, 1fr)",
      key: "user.readableId",
      selected: true,
    },
    {
      value: "cid",
      key: "user.ctrader_id",
      label: "Ctrader ID",
      gridColumnSize: "minmax(120px, 2fr)",
      selected: false,
      sortable: true,
    },
    {
      value: "firstName",
      key: "user.first_name",
      label: "First Name",
      gridColumnSize: "minmax(170px, 2fr)",
    },
    {
      value: "lastName",
      key: "user.last_name",
      label: "Last Name",
      gridColumnSize: "minmax(170px, 2fr)",
    },
    {
      value: "email",
      key: "user.email",
      label: "Email",
      gridColumnSize: "minmax(200px, 2fr)",
      selected: true,
      sortable: true,
    },
    {
      value: "requestType",
      key: "request_type",
      label: "Request Type",
      gridColumnSize: "minmax(200px, 2fr)",
      selected: true,
      sortable: true,
    },
    {
      value: "description",
      key: "metadata.description",
      label: "Description",
      gridColumnSize: "minmax(200px, 2fr)",
      selected: true,
    },
    {
      value: "createdAt",
      key: "createdAt",
      label: "Created At",
      gridColumnSize: "minmax(200px, 2fr)",
      selected: true,
      sortable: true,
    },
    {
      value: "updatedAt",
      key: "updatedAt",
      label: "Created At",
      gridColumnSize: "minmax(200px, 2fr)",
      sortable: true,
    },
    {
      value: "status",
      key: "status",
      label: "Status",
      gridColumnSize: "minmax(200px, 2fr)",
      selected: true,
    },
  ],
  WITHDRAW_REQUESTS: [
    {
      value: "requestId",
      key: "_id",
      label: "Request ID",
      gridColumnSize: "minmax(200px, 2fr)",
    },
    {
      value: "userId",
      key: "user._id",
      label: "User ID",
      gridColumnSize: "minmax(200px, 2fr)",
    },
    {
      value: "userReadableId",
      label: "Client ID",
      gridColumnSize: "minmax(100px, 1fr)",
      key: "user.readableId",
      selected: true,
    },
    {
      value: "account_id",
      key: "custom_account_id",
      label: "Account ID",
      gridColumnSize: "minmax(120px, 2fr)",
      selected: true,
      custom: true,
    },
    {
      value: "firstName",
      key: "user.first_name",
      label: "First Name",
      gridColumnSize: "minmax(170px, 2fr)",
    },
    {
      value: "lastName",
      key: "user.last_name",
      label: "Last Name",
      gridColumnSize: "minmax(170px, 2fr)",
    },
    {
      value: "email",
      key: "user.email",
      label: "Email",
      gridColumnSize: "minmax(300px, 2fr)",
      selected: true,
      sortable: true,
    },
    {
      value: "amount",
      key: "metadata.amount",
      label: "Amount",
      gridColumnSize: "minmax(100px, 2fr)",
      selected: true,
    },
    {
      value: "currency",
      key: "metadata.currency",
      label: "Currency",
      gridColumnSize: "minmax(100px, 2fr)",
      selected: true,
    },
    {
      value: "status",
      key: "status",
      label: "Status",
      gridColumnSize: "minmax(100px, 2fr)",
      selected: true,
    },
    {
      value: "createdAt",
      key: "createdAt",
      label: "Created At",
      gridColumnSize: "minmax(150px, 2fr)",
      selected: true,
      sortable: true,
    },
    {
      value: "updatedAt",
      key: "updatedAt",
      label: "Updated At",
      gridColumnSize: "minmax(150px, 2fr)",
      sortable: true,
    },
    {
      value: "transactionId",
      key: "metadata.transaction_id",
      label: "Transaction ID",
      gridColumnSize: "minmax(200px, 2fr)",
    },
    {
      value: "type",
      key: "metadata.type",
      label: "Type",
      gridColumnSize: "minmax(100px, 2fr)",
    },
    {
      value: "actions",
      label: "Actions",
      gridColumnSize: "minmax(150px, 2fr)",
      selected: true,
      custom: true,
      key: "kreper",
    },
  ],
  TRANSACTIONS: [
    {
      value: "transactionId",
      key: "_id",
      label: "Transaction ID",
      gridColumnSize: "minmax(200px, 2fr)",
    },
    {
      value: "readableId",
      label: "Client ID",
      selected: true,
      sortable: false,
      gridColumnSize: "minmax(100px, 1fr)",
      key: "user.readableId",
      custom: true,
    },
    {
      value: "account_id",
      label: "Account ID",
      selected: true,
      gridColumnSize: "minmax(130px, 2fr)",
      key: "userAccount.login_id",
    },
    {
      value: "userId",
      key: "user._id",
      label: "User ID",
      gridColumnSize: "minmax(200px, 2fr)",
    },
    {
      value: "firstName",
      key: "user.first_name",
      label: "First Name",
      gridColumnSize: "minmax(170px, 2fr)",
    },
    {
      value: "lastName",
      key: "user.last_name",
      label: "Last Name",
      gridColumnSize: "minmax(170px, 2fr)",
    },
    {
      value: "email",
      key: "user.email",
      label: "Email",
      gridColumnSize: "minmax(300px, 2fr)",
      selected: true,
    },
    {
      value: "accountId",
      key: "userAccount._id",
      label: "User Account",
      gridColumnSize: "minmax(200px, 2fr)",
    },
    {
      value: "loginId",
      key: "userAccount.login_id",
      label: "Login ID",
      gridColumnSize: "minmax(100px, 2fr)",
    },
    {
      value: "transactionType",
      key: "transaction_type",
      label: "Transaction Type",
      gridColumnSize: "minmax(150px, 2fr)",
    },
    {
      value: "intent",
      key: "intent",
      label: "Intent",
      gridColumnSize: "minmax(100px, 2fr)",
    },
    {
      value: "transactionStatus",
      key: "transaction_status",
      label: "Transaction Status",
      gridColumnSize: "minmax(170px, 2fr)",
      selected: true,
    },
    {
      value: "praxisTransactionId",
      key: "transaction_id",
      label: "Praxis Transaction Id",
      gridColumnSize: "minmax(200px, 2fr)",
    },
    {
      value: "processedCurrency",
      key: "processed_currency",
      label: "Processed Currency",
      gridColumnSize: "minmax(200px, 2fr)",
      selected: true,
    },
    {
      value: "processedAmount",
      key: "processed_amount",
      label: "Processed Amount",
      gridColumnSize: "minmax(200px, 2fr)",
      selected: true,
      sortable: true,
    },
    {
      value: "processedUsdConversionRate",
      key: "processed_usd_conversion_rate",
      label: "Processed USD Conversion Rate",
      gridColumnSize: "minmax(200px, 2fr)",
    },
    {
      value: "processedUsdAmount",
      key: "processed_usd_amount",
      label: "Processed USD Amount",
      gridColumnSize: "minmax(230px, 2fr)",
      selected: true,
      sortable: true,
    },
    {
      value: "fee",
      key: "fee",
      label: "Fee",
      gridColumnSize: "minmax(80px, 2fr)",
    },
    {
      value: "paymentMethod",
      key: "payment_method",
      label: "Payment Method",
      gridColumnSize: "minmax(200px, 2fr)",
      selected: true,
    },
    {
      value: "paymentProcessor",
      key: "payment_processor",
      label: "Payment Processor",
      gridColumnSize: "minmax(200px, 2fr)",
    },
    {
      value: "gateway",
      key: "gateway",
      label: "Gateway",
      gridColumnSize: "minmax(300px, 2fr)",
    },
    {
      value: "variable3",
      key: "variable3",
      label: "Promo Code",
      gridColumnSize: "minmax(150px, 2fr)",
    },
    {
      value: "createdAt",
      key: "createdAt",
      label: "Created At",
      gridColumnSize: "minmax(150px, 2fr)",
      sortable: true,
    },
    {
      value: "updatedAt",
      key: "updatedAt",
      label: "Updated At",
      gridColumnSize: "minmax(150px, 2fr)",
      selected: true,
      sortable: true,
    },
  ],
  FINANCES: [
    {
      value: "transactionId",
      key: "_id",
      label: "Transaction ID",
      gridColumnSize: "minmax(200px, 2fr)",
    },
    {
      value: "userReadableId",
      label: "Client ID",
      gridColumnSize: "minmax(100px, 2fr)",
      key: "user.readableId",
      selected: true,
    },
    {
      value: "cid",
      key: "user.ctrader_id",
      label: "Ctrader ID",
      gridColumnSize: "minmax(150px, 2fr)",
      sortable: true,
    },
    {
      value: "loginId",
      key: "userAccount.login_id",
      label: "Account",
      selected: true,
      gridColumnSize: "minmax(100px, 2fr)",
      selected: true,
    },
    {
      value: "userId",
      key: "user._id",
      label: "User ID",
      gridColumnSize: "minmax(200px, 2fr)",
    },
    {
      value: "accountId",
      key: "userAccount._id",
      label: "User Account",
      gridColumnSize: "minmax(200px, 2fr)",
    },
    {
      value: "firstName",
      key: "user.first_name",
      label: "First Name",
      gridColumnSize: "minmax(170px, 2fr)",
      selected: true,
    },
    {
      value: "lastName",
      key: "user.last_name",
      label: "Last Name",
      gridColumnSize: "minmax(170px, 2fr)",
      selected: true,
    },
    {
      value: "email",
      key: "user.email",
      label: "Email",
      gridColumnSize: "minmax(300px, 2fr)",
    },
    {
      value: "accountPlatform",
      key: "userAccount.platform",
      label: "Account Platform",
      gridColumnSize: "minmax(100px, 2fr)",
    },
    {
      value: "transactionType",
      key: "transaction_type",
      label: "Transaction Type",
      gridColumnSize: "minmax(200px, 2fr)",
      selected: true,
    },
    {
      value: "intent",
      key: "intent",
      label: "Intent",
      gridColumnSize: "minmax(100px, 2fr)",
    },
    {
      value: "transactionStatus",
      key: "transaction_status",
      label: "Transaction Status",
      gridColumnSize: "minmax(170px, 2fr)",
      selected: true,
    },
    {
      value: "praxisTransactionId",
      key: "transaction_id",
      label: "Praxis Transaction Id",
      gridColumnSize: "minmax(200px, 2fr)",
    },
    {
      value: "processedAmount",
      key: "processed_amount",
      label: "Processed Amount",
      gridColumnSize: "minmax(200px, 2fr)",
      selected: true,
      sortable: true,
    },
    {
      value: "processedCurrency",
      key: "processed_currency",
      label: "Processed Currency",
      gridColumnSize: "minmax(200px, 2fr)",
    },
    {
      value: "processedUsdConversionRate",
      key: "processed_usd_conversion_rate",
      label: "Processed USD Conversion Rate",
      gridColumnSize: "minmax(200px, 2fr)",
    },
    {
      value: "processedUsdAmount",
      key: "processed_usd_amount",
      label: "Processed USD Amount",
      gridColumnSize: "minmax(250px, 2fr)",
      sortable: true,
    },
    {
      value: "fee",
      key: "fee",
      label: "Fee",
      gridColumnSize: "minmax(80px, 2fr)",
      selected: true,
    },
    {
      value: "paymentMethod",
      key: "payment_method",
      label: "Payment Method",
      gridColumnSize: "minmax(200px, 2fr)",
      selected: true,
    },
    {
      value: "paymentProcessor",
      key: "payment_processor",
      label: "Payment Processor",
      gridColumnSize: "minmax(200px, 2fr)",
      selected: true,
    },
    {
      value: "gateway",
      key: "gateway",
      label: "Gateway",
      gridColumnSize: "minmax(300px, 2fr)",
      selected: true,
    },
    {
      value: "variable3",
      key: "variable3",
      label: "Promo Code",
      gridColumnSize: "minmax(150px, 2fr)",
    },
    {
      value: "other",
      key: "card.card_number",
      label: "Other",
      selected: true,
      sortable: false,
      gridColumnSize: "minmax(160px, 2fr)",
    },
    {
      value: "notes",
      key: "variable2",
      label: "Notes",
      selected: true,
      sortable: false,
      gridColumnSize: "minmax(160px, 2fr)",
    },
    {
      value: "createdAt",
      key: "createdAt",
      label: "TX Created At",
      gridColumnSize: "minmax(160px, 2fr)",
      selected: true,
      sortable: true,
    },
    {
      value: "updatedAt",
      key: "updatedAt",
      label: "TX Updated At",
      gridColumnSize: "minmax(160px, 2fr)",
      selected: true,
      sortable: true,
    },
    {
      value: "utm_campaign",
      key: "user.metadata.utm_campaign",
      label: "Utm Campaign",
      sortable: true,
      gridColumnSize: "minmax(170px, 2fr)",
    },
    {
      value: "utm_source",
      key: "user.metadata.utm_source",
      label: "Utm Source",
      sortable: true,
      gridColumnSize: "minmax(170px, 2fr)",
    },
    {
      value: "utm_medium",
      key: "user.metadata.utm_medium",
      label: "Utm Medium",
      sortable: true,
      gridColumnSize: "minmax(170px, 2fr)",
    },
    {
      value: "utm_term",
      key: "user.metadata.utm_term",
      label: "Utm Term",
      sortable: true,
      gridColumnSize: "minmax(170px, 2fr)",
    },
    {
      value: "utm_content",
      key: "user.metadata.utm_content",
      label: "Utm Content",
      sortable: true,
      gridColumnSize: "minmax(170px, 2fr)",
    },
  ],
  FIRST_TIME_DEPOSITS: [
    {
      value: "userReadableId",
      label: "Client ID",
      gridColumnSize: "minmax(100px, 1fr)",
      key: "user.readableId",
      selected: true,
    },
    {
      value: "firstName",
      label: "First Name",
      selected: true,
      sortable: true,
      gridColumnSize: "minmax(170px, 2fr)",
      key: "user.first_name",
      selected: true,
    },
    {
      value: "lastName",
      label: "Last Name",
      selected: true,
      sortable: true,
      gridColumnSize: "minmax(170px, 2fr)",
      key: "user.last_name",
    },
    {
      value: "email",
      key: "user.email",
      label: "Email",
      gridColumnSize: "minmax(200px, 2fr)",
    },
    {
      value: "country",
      key: "user.country",
      label: "Country",
      gridColumnSize: "minmax(120px, 2fr)",
      selected: true,
    },
    {
      value: "processedCurrency",
      key: "processed_currency",
      label: "Currency",
      gridColumnSize: "minmax(100px, 1fr)",
    },
    {
      value: "transactionType",
      key: "transaction_type",
      label: "Transaction Type",
      gridColumnSize: "minmax(200px, 2fr)",
      selected: true,
    },
    {
      value: "processedAmount",
      key: "processed_amount",
      label: "Amount",
      gridColumnSize: "minmax(100px, 1fr)",
      selected: true,
      sortable: true,
    },
    {
      value: "processedUsdAmount",
      key: "processed_usd_amount",
      label: "Amount (USD)",
      gridColumnSize: "minmax(180px, 1fr)",
      sortable: true,
    },
    {
      value: "paymentMethod",
      key: "payment_method",
      label: "Payment Method",
      gridColumnSize: "minmax(200px, 2fr)",
    },
    {
      value: "createdAt",
      key: "createdAt",
      label: "TX Created At",
      gridColumnSize: "minmax(150px, 2fr)",
      selected: true,
      sortable: true,
    },
    {
      value: "updatedAt",
      key: "updatedAt",
      label: "TX Updated At",
      gridColumnSize: "minmax(150px, 2fr)",
      selected: true,
      sortable: true,
    },
    {
      value: "utm_campaign",
      key: "user.metadata.utm_campaign",
      label: "Utm Campaign",
      selected: true,
      sortable: true,
      gridColumnSize: "minmax(170px, 2fr)",
    },
    {
      value: "utm_source",
      key: "user.metadata.utm_source",
      label: "Utm Source",
      selected: true,
      sortable: true,
      gridColumnSize: "minmax(170px, 2fr)",
    },
    {
      value: "utm_medium",
      key: "user.metadata.utm_medium",
      label: "Utm Medium",
      selected: true,
      sortable: true,
      gridColumnSize: "minmax(170px, 2fr)",
    },
    {
      value: "utm_term",
      key: "user.metadata.utm_term",
      label: "Utm Term",
      selected: true,
      sortable: true,
      gridColumnSize: "minmax(170px, 2fr)",
    },
    {
      value: "utm_content",
      key: "user.metadata.utm_content",
      label: "Utm Content",
      selected: true,
      sortable: true,
      gridColumnSize: "minmax(170px, 2fr)",
    },
  ],
  USER_FINANCES: [
    {
      value: "accountId",
      key: "userAccount._id",
      label: "User Account",
      gridColumnSize: "minmax(200px, 2fr)",
    },
    {
      value: "loginId",
      key: "userAccount.login_id",
      label: "Login ID",
      gridColumnSize: "minmax(100px, 2fr)",
    },
    {
      value: "transactionType",
      key: "transaction_type",
      label: "Transaction Type",
      gridColumnSize: "minmax(200px, 2fr)",
      selected: true,
    },
    {
      value: "intent",
      key: "intent",
      label: "Intent",
      gridColumnSize: "minmax(100px, 2fr)",
    },

    {
      value: "processedCurrency",
      key: "processed_currency",
      label: "Processed Currency",
      gridColumnSize: "minmax(170px, 2fr)",
      selected: true,
    },
    {
      value: "processedAmount",
      key: "processed_amount",
      label: "Processed Amount",
      gridColumnSize: "minmax(160px, 2fr)",
      selected: true,
      sortable: false,
    },
    {
      value: "processedUsdConversionRate",
      key: "processed_usd_conversion_rate",
      label: "Processed USD Conversion Rate",
      gridColumnSize: "minmax(200px, 2fr)",
    },
    {
      value: "processedUsdAmount",
      key: "processed_usd_amount",
      label: "Processed USD Amount",
      gridColumnSize: "minmax(250px, 2fr)",
      selected: false,
      sortable: true,
    },
    {
      value: "transactionStatus",
      key: "transaction_status",
      label: "Transaction Status",
      gridColumnSize: "minmax(120px, 2fr)",
      selected: true,
      sortable: false,
    },
    {
      value: "fee",
      key: "fee",
      label: "Fee",
      gridColumnSize: "minmax(80px, 2fr)",
    },
    {
      value: "fee_type",
      key: "fee_type",
      label: "Fee Reason",
      gridColumnSize: "minmax(200px, 2fr)",
    },
    {
      value: "paymentMethod",
      key: "payment_method",
      label: "Payment Method",
      gridColumnSize: "minmax(190px, 2fr)",
      selected: true,
    },
    {
      value: "variable1",
      key: "variable1",
      label: "Comment",
      gridColumnSize: "minmax(150px, 2fr)",
      selected: true,
    },
    {
      value: "paymentProcessor",
      key: "payment_processor",
      label: "Payment Processor",
      gridColumnSize: "minmax(200px, 2fr)",
    },
    {
      value: "gateway",
      key: "gateway",
      label: "Gateway",
      gridColumnSize: "minmax(300px, 2fr)",
    },
    {
      value: "variable3",
      key: "variable3",
      label: "Promo Code",
      gridColumnSize: "minmax(150px, 2fr)",
    },
    {
      value: "variable2",
      key: "variable2",
      label: "Reject Reason",
      gridColumnSize: "minmax(150px, 2fr)",
    },
    {
      value: "notes",
      key: "card.card_number",
      label: "Notes/Other",
      selected: true,
      sortable: false,
      gridColumnSize: "minmax(120px, 2fr)",
    },
    {
      value: "praxisTransactionId",
      key: "transaction_id",
      label: "Praxis Transaction Id",
      gridColumnSize: "minmax(200px, 2fr)",
    },
    {
      value: "transactionId",
      key: "_id",
      label: "Transaction ID",
      gridColumnSize: "minmax(200px, 2fr)",
      selected: true,
    },
    {
      value: "refund",
      key: "refund_amount",
      label: "Refund",
      selected: true,
      gridColumnSize: "minmax(80px, 2fr)",
    },
    {
      value: "createdAt",
      key: "createdAt",
      label: "Created At",
      gridColumnSize: "minmax(145px, 2fr)",
      sortable: true,
    },
    {
      value: "updatedAt",
      key: "updatedAt",
      label: "Updated At",
      gridColumnSize: "minmax(145px, 2fr)",
      selected: true,
      sortable: true,
    },
    {
      value: "actions",
      label: "Actions",
      gridColumnSize: "minmax(100px, 2fr)",
      selected: true,
      custom: true,
      key: "kreper",
      permissions: [PERMISSIONS.USERS.refund_transaction],
    },
  ],
  UTMS: [
    {
      value: "readableId",
      label: "Client ID",
      gridColumnSize: "minmax(100px, 1fr)",
      key: "readableId",
      selected: true,
    },
    {
      value: "firstName",
      label: "First Name",
      selected: true,
      sortable: true,
      gridColumnSize: "minmax(170px, 2fr)",
      key: "first_name",
      selected: true,
    },
    {
      value: "lastName",
      label: "Last Name",
      selected: true,
      sortable: true,
      gridColumnSize: "minmax(170px, 2fr)",
      key: "last_name",
      selected: true,
    },
    {
      value: "email",
      label: "Email",
      selected: true,
      sortable: true,
      gridColumnSize: "minmax(300px, 2fr)",
      key: "email",
      selected: true,
    },
    {
      value: "utm_campaign",
      label: "Utm Campaign",
      selected: true,
      sortable: true,
      gridColumnSize: "minmax(170px, 2fr)",
      key: "metadata.utm_campaign",
      selected: true,
    },
    {
      value: "utm_source",
      label: "Utm Source",
      selected: true,
      sortable: true,
      gridColumnSize: "minmax(170px, 2fr)",
      key: "metadata.utm_source",
      selected: true,
    },
    {
      value: "utm_medium",
      label: "Utm Medium",
      selected: true,
      sortable: true,
      gridColumnSize: "minmax(170px, 2fr)",
      key: "metadata.utm_medium",
      selected: true,
    },
    {
      value: "utm_term",
      label: "Utm Term",
      selected: true,
      sortable: true,
      gridColumnSize: "minmax(170px, 2fr)",
      key: "metadata.utm_term",
      selected: true,
    },
    {
      value: "utm_content",
      label: "Utm Content",
      selected: true,
      sortable: true,
      gridColumnSize: "minmax(170px, 2fr)",
      key: "metadata.utm_content",
      selected: true,
    },
    {
      value: "createdAt",
      label: "Created At",
      selected: true,
      sortable: true,
      gridColumnSize: "minmax(150px, 2fr)",
      key: "createdAt",
      selected: true,
    },
  ],
  BALANCE_REPORT: [
    {
      value: "readableId",
      label: "Client ID",
      gridColumnSize: "minmax(100px, 1fr)",
      key: "readableId",
      selected: true,
    },
    {
      value: "email",
      label: "Email",
      gridColumnSize: "minmax(270px, 1fr)",
      key: "email",
      selected: true,
    },
    {
      value: "balanceCtraderUSD",
      label: "Balance Ctrader USD",
      gridColumnSize: "minmax(160px, 1fr)",
      key: "balanceCtraderUSD",
      selected: true,
    },
    {
      value: "balanceMt4USD",
      label: "Balance MT4 USD",
      gridColumnSize: "minmax(160px, 1fr)",
      key: "balanceMt4USD",
      selected: true,
    },
    {
      value: "balanceMt5USD",
      label: "Balance MT5 USD",
      gridColumnSize: "minmax(160px, 1fr)",
      key: "balanceMt5USD",
      selected: true,
    },
    {
      value: "equityCtraderUSD",
      label: "Equity Ctrader USD",
      gridColumnSize: "minmax(160px, 1fr)",
      key: "equityCtraderUSD",
      selected: true,
    },
    {
      value: "equityMt4USD",
      label: "Equity MT4 USD",
      gridColumnSize: "minmax(160px, 1fr)",
      key: "equityMt4USD",
      selected: true,
    },
    {
      value: "equityMt5USD",
      label: "Equity MT5 USD",
      gridColumnSize: "minmax(160px, 1fr)",
      key: "equityMt5USD",
      selected: true,
    },
  ],
  DOCUMENTS: [
    {
      value: "readableId",
      label: "Client ID",
      gridColumnSize: "minmax(50px, 1fr)",
      key: "user.readableId",
      selected: true,
    },
    {
      value: "first_name",
      label: "First Name",
      gridColumnSize: "minmax(100px, 1fr)",
      key: "user.first_name",
      selected: true,
    },
    {
      value: "last_name",
      label: "Last Name",
      gridColumnSize: "minmax(100px, 1fr)",
      key: "user.last_name",
      selected: true,
    },
    {
      value: "document_type",
      label: "Type",
      gridColumnSize: "minmax(100px, 1fr)",
      key: "document_type",
      selected: true,
    },
    // {
    //   value: "status",
    //   label: "Status",
    //   gridColumnSize: "minmax(100px, 1fr)",
    //   key: "status",
    //   selected: true,
    // },
    {
      value: "updatedAt",
      label: "Timestamp",
      gridColumnSize: "minmax(100px, 1fr)",
      key: "updatedAt",
      selected: true,
    },
    {
      value: "_id",
      label: "Document",
      gridColumnSize: "minmax(100px, 1fr)",
      key: "_id",
      selected: true,
    },
    {
      value: "actions",
      label: "Actions",
      gridColumnSize: "minmax(350px, 1fr)",
      key: "custom_actions",
      selected: true,
      custom: true,
    },
  ],
};

export default availableFields;
